# Generated by Django 5.2.1 on 2025-06-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupLogin', '0002_farmerproduct_merchantrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantrequest',
            old_name='posted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='merchantrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
