# Generated by Django 5.2.1 on 2025-06-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupLogin', '0003_rename_posted_at_merchantrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('merchant', 'Merchant')], max_length=20),
        ),
    ]
