# Generated by Django 5.2.1 on 2025-06-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupLogin', '0005_farmerproduct_user_merchantrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerproduct',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
