# Generated by Django 5.2.1 on 2025-06-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupLogin', '0006_farmerproduct_latitude_farmerproduct_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantrequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantrequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
